Rasterized versions of ggbeeswarm
VPetukhov/ggrastr pull request #1
Opened 2018-08-16 00:03 UTC by kpjonsson

I thought this would be a neat implementation. Not sure it was the neatest way to do it though, I struggle with retaining the aspect ratios of rasterized points.

2018-08-16 10:36 UTC, VPetukhov requested changes
Hi, thank you very much for contribution!

Here are some comments on the code for `geom_beeswarm`. Could you please address them and the same issues for `geom_quasirandom`?

2018-08-16 10:36 UTC, VPetukhov commented on R/geom-beeswarm-rast.R
> +DrawGeomPointRast <- function(data, panel_params, coord, na.rm = FALSE, width=NULL, height=NULL, dpi=300) {
Looks like this function is completely the same as in `geom_point_rast`. In this case, you don't need to redefine it.

2018-08-16 10:36 UTC, VPetukhov commented on R/geom-beeswarm-rast.R
> +GeomPointRast <- ggplot2::ggproto(
The same, you don't need to redefine this class.

2018-08-16 10:36 UTC, VPetukhov commented on R/geom-beeswarm-rast.R
> +  position <- ggbeeswarm::position_beeswarm(priority = priority, cex = cex,
Now your functions depend on `ggbeeswarm`. This means you need to add it to `Suggests` section of the `DESCRIPTION` file. Also, you need to check if this package is installed before using it (see [Hadley's guide](http://r-pkgs.had.co.nz/description.html#dependencies)).

2018-08-16 10:36 UTC, VPetukhov commented on R/geom-beeswarm-rast.R
> +#' This geom is similar to \code{\link[ggplot2]{geom_point}}, but creates a raster layer
Don't you mean `ggbeeswarm::position_beeswarm` here?

2018-08-16 10:36 UTC, VPetukhov commented on R/geom-beeswarm-rast.R
> +#' ggplot() + geom_point_rast(aes(x=rnorm(1000), y=rnorm(1000)), dpi=600)
Could you please add a valid example?

2018-08-16 12:15 UTC, kpjonsson commented
@VPetukhov Thanks for the helpful comments. I think I've addressed this, can you check?

2018-08-17 10:45 UTC, VPetukhov approved these changes

2018-08-17 10:45 UTC, merged

2018-08-17 11:05 UTC, VPetukhov commented
@kpjonsson Thank you for the quick fix! Merged your changes. There was a single issue, which you didn't fix: adding `ggbeeswarm` to Suggest section of the DESCRIPTION file, so I added it in f490890a6b7eac85bab6d45f5ff6bbea92781f88.

2018-08-17 11:25 UTC, kpjonsson commented
Great, thanks!